Set routes in main.py
codex-team/codex.bot pull request #20
Opened 2017-05-05 18:08 UTC by talyguryn

# Conflicts:
#	includes/telegram/telegram.py

2017-05-05 20:34 UTC, n0str requested changes

2017-05-05 20:34 UTC, n0str commented on codexbot/core.py
> +                try:
Зачем ещё один try? Там внешний есть с тем же поведением

2017-05-05 20:34 UTC, n0str commented on codexbot/services/telegram/telegram.py
> +    def get_routes(self):
Лучше в __init__ методе установить сразу роуты. Сейчас поведение получается неверное. Функция, которая устанавливает роуты называется get_routes

2017-05-06 08:18 UTC, n0str requested changes

2017-05-06 08:18 UTC, n0str commented on codexbot/core.py
> +                # get routes for this module
Написано get, а делается set.

2017-05-06 08:22 UTC, n0str approved these changes

2017-05-06 09:32 UTC, khaydarov approved these changes

2017-05-06 09:34 UTC, gohabereg approved these changes

2017-05-06 11:33 UTC, neSpecc approved these changes

2017-05-06 11:35 UTC, merged