using slackClient to make the connection
codex-team/codex.bot pull request #24
Opened 2017-05-06 21:43 UTC by khaydarov

2017-05-17 18:41 UTC, talyguryn approved these changes

2017-06-14 18:07 UTC, neSpecc approved these changes

2017-06-14 18:07 UTC, neSpecc commented on codexbot/services/slack/slack.py
> +        # confirm event subscription
After hand-filling command in api.slack.com/apps, we got verification request wth 'challenge' and 'token'. To verify, pass back 'challenge' field.

https://api.slack.com/events/url_verification

2017-06-14 18:46 UTC, n0str approved these changes

2017-06-14 18:53 UTC, gohabereg requested changes

2017-06-14 18:53 UTC, gohabereg commented on codexbot/services/slack/Bot.py
> +            }, {
Поправь выравнивание

2017-06-14 18:53 UTC, gohabereg commented on codexbot/services/slack/slack.py
> +                'type': 'private' if params['post']['channel_name'] == 'directmessage' else 'group'  # --- private or channel
Вынеси в отдельную переменную

2017-06-14 18:56 UTC, gohabereg approved these changes

2017-06-14 18:57 UTC, merged