Telegram message handle
codex-team/codex.bot pull request #34
Opened 2017-05-18 13:48 UTC by gohabereg

2017-05-18 14:21 UTC, n0str requested changes

2017-05-18 14:21 UTC, n0str commented on codexbot/broker/broker.py
> +                return
Имел в виду continue?

2017-05-19 18:33 UTC, neSpecc approved these changes

2017-05-19 18:40 UTC, n0str approved these changes

2017-05-19 18:40 UTC, merged